[keys.insert]
f = { d = "normal_mode" } # Maps `ga` to show possible code actions

[keys.normal]
# Muscle memory
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
